# Generated by Django 4.2.28 on 2026-02-23 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('upload', 'Upload')], default='live', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_reps', models.IntegerField(default=0)),
                ('avg_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('posture_ok', models.BooleanField(default=False)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_reps', models.IntegerField(default=0)),
                ('feedback_message', models.CharField(blank=True, max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to='api.user')),
            ],
            options={
                'db_table': 'video_uploads',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.user'),
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.IntegerField()),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('posture_ok', models.BooleanField(default=False)),
                ('feedback_message', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='api.session')),
            ],
            options={
                'db_table': 'reps',
            },
        ),
        migrations.CreateModel(
            name='ExerciseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture_ok', models.BooleanField(default=False)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feedback_message', models.CharField(blank=True, max_length=500)),
                ('counter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.session')),
            ],
            options={
                'db_table': 'exercise_feedback',
            },
        ),
    ]
