# Generated by Django 4.2.28 on 2026-02-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='height_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
