# Generated by Django 5.2.12 on 2026-04-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
